---

name: build zip

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8
      - name: build
        uses: ./.github/actions/build-keycloak
        with:
          upload-m2-repo: true
          upload-dist: true

      - name: Build Docker image preparation
        run: |
          version=$(ls quarkus/dist/target/keycloak-*.tar.gz | cut -d'/' -f4 | sed "s/keycloak-\(.*\).tar.gz/\1/")
          echo "keycloak_version=${version,,}" >> $GITHUB_ENV
          cp $GITHUB_WORKSPACE/quarkus/dist/target/keycloak-${version}.tar.gz .
      #     cd $GITHUB_WORKSPACE/quarkus/container
      #     docker build --build-arg KEYCLOAK_DIST=keycloak-${version}.tar.gz -t ${version} .
      - name: Build docker image
        uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.2
        with:
          ref: ${{ github.ref }}
          component: '[{"name": "keycloak", "file": "./quarkus/container/Dockerfile", "context": "--build-arg KEYCLOAK_DIST=keycloak-${version}.tar.gz ./quarkus/container"}]'
          tags: ${{ env.keycloak_version }}

