---

name: build zip

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup JDK
      #   uses: actions/setup-java@v4
      #   with:
      #     distribution: adopt
      #     java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8
      - name: build
        uses: ./.github/actions/build-keycloak
        with:
          upload-m2-repo: true
          upload-dist: true

      - name: Build Docker image preparation
        run: |
          version=$(ls quarkus/dist/target/keycloak-*.tar.gz | cut -d'/' -f4 | sed "s/keycloak-\(.*\).tar.gz/\1/")
          echo "keycloak_version=${version,,}" >> $GITHUB_ENV
          cp $GITHUB_WORKSPACE/quarkus/dist/target/keycloak-*.tar.gz $GITHUB_WORKSPACE/quarkus/container

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          context: ${{ github.workspace }}/quarkus/container
          file: ${{ github.workspace }}/quarkus/container/Dockerfile
          build-args: |
            KEYCLOAK_DIST=${{ github.workspace }}/quarkus/container/keycloak-${{ env.keycloak_version }}.tar.gz
          push: 'true'
          tags: keycloak:${{ env.keycloak_version }},${{ github.repository }}:${{ github.workflow_sha }}
          platforms: linux/amd64

      # - name: Build docker image
      #   uses: netcracker/qubership-workflow-hub/actions/docker-action@v1.0.2
      #   with:
      #     ref: ${{ github.ref }}
      #     component: '[{"name": "keycloak", "file": "./quarkus/container/Dockerfile", "context": "--build-arg KEYCLOAK_DIST ./quarkus/container"}]'
      #     tags: ${{ env.keycloak_version }}
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #     KEYCLOAK_DIST: keycloak-${{ env.keycloak_version }}.tar.gz
