---

name: build zip

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: 21
      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8
      - name: build
        run: |
          ./mvnw clean install -Pdistribution -Dskip.tests=true
      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: ${{ github.workspace }}/quarkus/dist/target/keycloak-*.zip
          name: keykloak
      - name: Build Docker image
        run: |
          version=$(ls quarkus/dist/target/keycloak-*.tar.gz | cut -d'/' -f4 | sed "s/keycloak-\(.*\).tar.gz/\1/")
          echo "keycloak_version=${version}" >> $GITHUB_ENV
          cp $GITHUB_WORKSPACE/quarkus/dist/target/keycloak-${version}.tar.gz .
          cd $GITHUB_WORKSPACE/quarkus/container
          docker build --build-arg KEYCLOAK_DIST=keycloak-${version}.tar.gz -t ${version} .
      - name: Build docker image
        uses: qubership-workflow-hub/actions/docker-action@1.0.2
        with:
          ref: ${{ github.ref }}
          component: '[{"name": "keycloak", "file": "./quarkus/container/Dockerfile", "context": "--build-arg KEYCLOAK_DIST=keycloak-${version}.tar.gz ./quarkus/container"}]'
          tags: ${{ env.keycloak_version }}

